name: Rust

on:
  push:
    branches: [ main ]
    paths: [ './rust/*' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      working-directory: rust
      run: cargo test --verbose
